name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Package
        run: ./package.sh
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.zip
